import * as tokens from "../grammars/rockstar.terms.js"

const aliases = new Map();
aliases.set(tokens.Above, ['above', 'over']);
aliases.set(tokens.And, ['and']);
aliases.set(tokens.Around, ['around', 'round']);
aliases.set(tokens.As, ['as']);
aliases.set(tokens.Great, ['great', 'high', 'big', 'strong']);
aliases.set(tokens.Small, ['less', 'low', 'small', 'weak']);
aliases.set(tokens.At, ['at']);
aliases.set(tokens.Back, ['back']);
aliases.set(tokens.Be, ['be']);
aliases.set(tokens.Break, ['break']);
aliases.set(tokens.Build, ['build']);
aliases.set(tokens.Call, ['call']);
aliases.set(tokens.Cast, ['cast', 'burn']);
aliases.set(tokens.Continue, ['continue', 'take']);
aliases.set(tokens.Debug, ['debug']);
aliases.set(tokens.Divided, ['divided', 'between', 'over']);
aliases.set(tokens.Down, ['down']);
aliases.set(tokens.Else, ['else', 'otherwise']);
aliases.set(tokens.Empty, ['empty', 'silent', 'silence']);
aliases.set(tokens.End, ['end', 'yeah', 'baby', 'oh']);
aliases.set(tokens.Exactly, ['exactly', 'totally', 'really']);
aliases.set(tokens.False, ["false", "lies", "no", "wrong"]);
aliases.set(tokens.His, ['his', 'her']);
aliases.set(tokens.If, ['if', 'when']);
aliases.set(tokens.Into, ['into', 'in']);
aliases.set(tokens.Is, ['is', 'was', 'are', 'were', 'am']);
aliases.set(tokens.Isnt, ["isnt", "isn't", 'aint', "ain't", "wasn't", "wasnt", "aren't", "arent", "weren't", "werent"]);
aliases.set(tokens.Join, ['join', 'unite']);
aliases.set(tokens.Knock, ['knock']);
aliases.set(tokens.Less, ['less', 'lower', 'smaller', 'weaker']);
aliases.set(tokens.Let, ['let']);
aliases.set(tokens.Like, ['like', 'so']);
aliases.set(tokens.Listen, ['listen']);
aliases.set(tokens.Minus, ['minus', 'without']);
aliases.set(tokens.More, ['greater', 'higher', 'bigger', 'stronger', 'more']);
aliases.set(tokens.Mysterious, ['mysterious']);
aliases.set(tokens.Non, ['non']);
aliases.set(tokens.Nor, ['nor']);
aliases.set(tokens.Not, ['not']);
aliases.set(tokens.Now, ['now']);
aliases.set(tokens.Null, ['null', 'nothing', 'nowhere', 'nobody', 'gone']);
aliases.set(tokens.Or, ['or']);
aliases.set(tokens.Over, ['over']);
aliases.set(tokens.Plus, ['plus', 'with']);
aliases.set(tokens.Pop, ['roll', 'pop']);
aliases.set(tokens.Print, ["print", "shout", "say", "scream", "whisper"]);
aliases.set(tokens.Pronoun, ['they', 'them', 'she', 'him', 'her', 'hir', 'zie', 'zir', 'xem', 'ver', 'ze', 've', 'xe', 'it', 'he', 'you', 'me', 'i']);
aliases.set(tokens.Push, ['rock', 'push']);
aliases.set(tokens.Put, ['put']);
aliases.set(tokens.Return, ['return', 'giving', 'give', 'send']);
aliases.set(tokens.Says, ['say', 'says', 'said']);
aliases.set(tokens.Split, ['cut', 'split', 'shatter']);
aliases.set(tokens.Takes, ['takes', 'wants']);
aliases.set(tokens.Taking, ['taking']);
aliases.set(tokens.Than, ['than']);
aliases.set(tokens.The, ['an', 'a', 'the', 'my', 'your', 'our', 'their']);
aliases.set(tokens.Then, ['then']);
aliases.set(tokens.Times, ['times', 'of']);
aliases.set(tokens.To, ['to']);
aliases.set(tokens.True, ["true", "yes", "ok", "right"]);
aliases.set(tokens.Turn, ['turn']);
aliases.set(tokens.Under, ['under', 'below']);
aliases.set(tokens.Until, ['until']);
aliases.set(tokens.Up, ['up']);
aliases.set(tokens.Using, ['using', 'with']);
aliases.set(tokens.While, ['while']);
aliases.set(tokens.With, ['with']);
aliases.set(tokens.Write, ['write']);

const keywords = Array.from(aliases.values()).flat();

export { aliases, keywords }