source 'https://rubygems.org'

gem "jekyll", "~> 4.3.3" # installed by `gem jekyll`

gem "just-the-docs", "0.8.2" # pinned to the current release

gem 'wdm', '>= 0.1.0', platforms: [:mingw, :mswin, :x64_mingw, :jruby]