// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {Variables, Operators, PoeticNumber, PoeticString, EOB, EOS, Wildcard, Keywords} from "../tokenizers/rockstar-tokenizer"
import {highlighting} from "./rockstar-highlight.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "*hO!TQ)aOOP![O&jOOOOQ$y'#Eq'#EqO!dQ)`O'#EVO!iQ)aO'#EaO#^Q)aO'#EbO#eQ'|O'#EcO#jQ'|O'#EdO!iQ)aO'#EeO!iQ)aO'#EgO#oQ)`O'#EgOOQ$w'#EU'#EUO!iQ)aO'#EUO#wQ*cO'#ETO$UQ&zOOQOQ&jOOPOOO'#EP'#EPPOOO)C@e)C@eO$^Q&kO,5:qO$lQ)bO'#E^OOQQ'#E_'#E_OOQQ'#EZ'#EZO$zQ&lO'#EYOOQ$y'#EX'#EXOOQ$w,5:{,5:{OOQ$w,5:|,5:|O!iQ)aO,5:|OOQ$w,5:},5:}OOQ$w,5;O,5;OO%VQ*RO,5;PO%^Q)`O,5;RO%cQ&rO,5;RO%hQ)fO,5;ROOQ$w,5:p,5:pOOQ$g'#Ej'#EjO%VQ*RO'#EkOOQ$w'#Ek'#EkO%yQ*cO,5:oOOQ$w,5:o,5:oOOQ$V'#Em'#EmO&TQ)qO'#ElO$UQ&zOOO&[Q*cO'#EpOOQ$w1G0]1G0]O'uQ)bO,5:xO!iQ)aO'#EWOOQ$y'#Ei'#EiOOQ#u'#E`'#E`O!iQ)aO,5:tOOQ$w1G0h1G0hO%VQ*RO'#EfOOQ$w'#Ef'#EfOOQ$w1G0k1G0kO$^Q&kO1G0mOOQ#u1G0m1G0mO!iQ)aO1G0mO$^Q&kO1G0mOOQ$g-E8h-E8hOOQ$w,5;V,5;VOOQ$w-E8i-E8iOOQ$w1G0Z1G0ZOOQ$V-E8k-E8kOOQ`,5;W,5;WOOQ`-E8j-E8jO(TQ*cO,5;[OOQ$y-E8g-E8gOOQ$y,5:r,5:rOOQ$y1G0`1G0`OOQ$w,5;Q,5;QOOQ#u7+&X7+&XO)nQ)`O7+&XO!iQ)aO<<IsOOQ#uAN?_AN?_",
  stateData: ")s~O!rOS!tPQ!uPQ~OPQOQQORQOSQOdUOhVO|RO!ZSO!]XO!^TO!lWO!oWO~O#[_O~P]O!t`O!u`O~O!hbO~OPQOQQORQOSQOmdOpdO!PdO!UdO!idO#OeO#PeO~ObjO~P!iO[kO~O[lO~OupO!_oO~OYvOZrO#[vO~P]OYwO#[_O~OPQOQQORQOSQO~Oa}OT#QXU#QXV#QX~OT!POU!POV!PO~OZrO~P]Ot!VO~OX!WO~OT!POU!POV!POW!YO!T!XO~OY!^OZrO~P]OYwO~P]Oa}OP#dXQ#dXR#dXS#dXY#dXZ#dXd#dXh#dX|#dX!Z#dX!]#dX!^#dX!l#dX!o#dX#[#dXm#dXp#dX!P#dX!U#dX!i#dX#O#dX#P#dX~Oa}OT#QaU#QaV#Qa~Oa}OP#daQ#daR#daS#daY#daZ#dad#dah#da|#da!Z#da!]#da!^#da!l#da!o#da#[#dam#dap#da!P#da!U#da!i#da#O#da#P#da~Ou!iO~O",
  goto: "'v#fPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#gPPP#j#s$S$]$c%O%^PP%j%j%v$S$S$S$S$S%|&PP&Y&d&o&u&{PP'S'YRaPQ^OQ!`xR!f!SU]Ox!SSt]uQ!TmR![s_ZO]msux!SX!Ocz|!bQhSQiTQmWQnXQq[Q!RjQ!d}Q!g!XR!j!ibgSTWX[j}!X!iR!e!QefSTWX[j}!Q!X!ieeSTWX[j}!Q!X!iQ!QfR!XpR!Um_[O]msux!SQ|cQ!bzT!c|!bSs]uQ!SmT!Zs!SQu]R!]uQy^R!aySx^yR!_xQ{bR!g!V^YO]msux!SdcSTWX[j}!Q!X!iSzb!VR!h!Y",
  nodeNames: "⚠ ProperVariable CommonVariable SimpleVariable Pronoun LogicOperator CompareOperator ArithmeticOperator PoeticNumber PoeticString EOB EOS Wildcard Above And Around As At Back Be Break Build Call Cast Continue Debug Divided Down Else Empty End Exactly False Great His If Into Is Isnt Join Knock Less Let Like Listen Minus More Mysterious Non Nor Not Now Null Or Over Plus Pop Print Push Put Return Says Small Split Takes Taking Than The Then Times To True Turn Under Until Up Using While With Write Whitespace Comment LineComment BlockComment Program Block Statement ListenStatement Indexer Expression Binary Primary String Number Lookup Constant Operator OutputStatement ReturnStatement BreakStatement ContinueStatement LoopStatement Body Assignment EOF",
  maxTerm: 113,
  propSources: [highlighting],
  skippedNodes: [0,13,14,15,16,19,21,22,23,25,26,27,28,30,31,33,34,35,38,39,40,41,42,43,45,46,48,49,50,53,54,55,56,58,62,63,64,65,66,67,68,69,72,73,75,76,78,79,80,81,82,83],
  repeatNodeCount: 5,
  tokenData: "&t~R[XYwYZw]^wpqwrs!Yst#vxy$e!O!P%S!Q![%b!}#O%m#o#p&V~~&o~|S!r~XYwYZw]^wpqw~!]VOr!Yrs!rs#O!Y#O#P!w#P;'S!Y;'S;=`#p<%lO!Y~!wO#O~~!zRO;'S!Y;'S;=`#T;=`O!Y~#WWOr!Yrs!rs#O!Y#O#P!w#P;'S!Y;'S;=`#p;=`<%l!Y<%lO!Y~#sP;=`<%l!Y~#yTOY#vYZ$YZ;'S#v;'S;=`$_<%lO#v~$_O!t~~$bP;=`<%l#v~$hTOy$eyz$wz;'S$e;'S;=`$|<%lO$e~$|O!u~~%PP;=`<%l$e~%VP!Q![%Y~%_P#P~!Q![%Y~%gQ#P~!O!P%S!Q![%b~%pTO#P%m#P#Q$w#Q;'S%m;'S;=`&P<%lO%m~&SP;=`<%l%m~&YTO#q&V#q#r$w#r;'S&V;'S;=`&i<%lO&V~&lP;=`<%l&V~&tO#[~",
  tokenizers: [Variables, Operators, PoeticNumber, PoeticString, EOB, EOS, Wildcard, Keywords, 0],
  topRules: {"Program":[0,84]},
  tokenPrec: 0
})
