name: build-windows-binary
on:
  workflow_call:
    inputs:
      rockstar_version:
        required: true
        type: string
        default: "v0.0.0-test"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: update version constant
        run: |
          (Get-content Starship/Rockstar.Engine/RockstarEnvironment.cs)
          | Foreach-Object {$_ -replace "VERSION = ""[^""]+"";", "VERSION = ""${{ github.events.inputs.rockstar_version }}"";"}
          | Set-Content Starship/Rockstar.Engine/RockstarEnvironment.cs
      - name: dotnet publish Windows x64 binary
        run: dotnet publish Starship/Rockstar -o rockstar-windows-x64-binary -c Release
      - name: Test Windows x64 binary
        run:
          rockstar-windows-x64-binary/rockstar.exe --version
      - uses: actions/cache/save@v4
        name: save rockstar-windows-x64-binary to cache
        id: save-rockstar-windows-x64-binary-to-cache
        with:
          enableCrossOsArchive: true
          path: rockstar-windows-x64-binary
          key: rockstar-windows-x64-binary-${{ github.run_id }}
