name: build-macos-binary
on:
  workflow_call:
    inputs:
      rockstar_version:
        required: true
        type: string
        default: "v0.0.0-test"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Patch VERSION constant inside Starship/Rockstar.Engine/RockstarEnvironment.cs
        run: sed -i "" 's/VERSION = "[^"]*";/VERSION = "${{ inputs.rockstar_version }}";/g' Starship/Rockstar.Engine/RockstarEnvironment.cs
      - name: dotnet publish macos x64 binary
        run: dotnet publish Starship/Rockstar -o rockstar-macos-x64-binary -r osx-x64 -c Release
      - name: dotnet publish macos ARM64 binary
        run: dotnet publish Starship/Rockstar -o rockstar-macos-arm64-binary -r osx-arm64 -c Release
      - name: Test ARM64 binary
        run:
          rockstar-macos-arm64-binary/rockstar --version
      - uses: actions/cache/save@v4
        name: Save rockstar-macos-x64-binary to cache
        id: save-rockstar-macos-x64-binary-to-cache
        with:
          enableCrossOsArchive: true
          path: rockstar-macos-x64-binary
          key: rockstar-macos-x64-binary-${{ github.run_id }}
      - uses: actions/cache/save@v4
        name: Save rockstar-macos-arm64-binary to cache
        id: save-rockstar-macos-arm64-binary-to-cache
        with:
          enableCrossOsArchive: true
          path: rockstar-macos-arm64-binary
          key: rockstar-macos-arm64-binary-${{ github.run_id }}
